baseurl: https://portfolio.blogzip.net
languageCode: en-us
paginate: 5
title: Example Site

languages:
  en:
    languageName: English
    title: jinsoo-youn
    weight: 1
DefaultContentLanguage: en
module:
  # uncomment line below for temporary local development of module
  # replacements: "github.com/CaiJimmy/hugo-theme-stack/v3 -> ../../hugo-theme-stack"
  imports:
    - path: github.com/CaiJimmy/hugo-theme-stack/v3
      disable: false

params:
  sidebar:
    emoji: 🍥
    subtitle: jinwoo's Daddy
    avatar:
      enabled: true
      local: true
      src: main.jpg

    colorScheme:
      # Display toggle
      toggle: true
      default: auto

#  mainSections:
#    - post
#  featuredImageField: image
#  rssFullContent: true
#  favicon:
#
#  footer:
#    since: 2020
#    customText:


menu:
  main: []
#  main:
#    name: title

  social:
    - identifier: github
      name: GitHub
      url: https://github.com/jinsoo-youn
      params:
        icon: brand-github

    - identifier: home
      name: Home
      url: https://woody.blogzip.net
      params:
        icon: home

markup:
  goldmark:
    renderer:
      ## Set to true if you have HTML content inside Markdown
      unsafe: false
  tableOfContents:
    endLevel: 4
    ordered: true
    startLevel: 2
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    tabWidth: 4